services:
  auth-service:
    container_name: auth-service
    environment:
      - PORT=7001
    env_file:
      - ./.env
    networks:
      - auth-service-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: my-mysql-auth-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - auth-service-sql-data:/var/lib/mysql
    networks:
      - auth-service-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my-phpmyadmin-auth-service
    restart: unless-stopped # //* Doesn’t restart if you manually stop it
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: mypassword
    networks:
      - auth-service-network

networks:
  auth-service-network:
volumes:
  auth-service-sql-data:

# =======================================================================================
# ============================== Commands ===============================================
# =======================================================================================

# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml down
# docker exec -it blog-app bash
# docker logs blog-app -f
