services:
  auth-service:
    image: auth-service:build
    build:
      context: .
      target: builder

#* How should we defined here volumes and networks ???
#* And should we defined them here or in prod ????
